name: DisasterSMP
version: 1.0
main: org.example.DisasterPlugin
api-version: 1.21
folia-supported: true
commands:
  disaster:
    description: Activeer een natuurlijke ramp
    usage: /disaster
permissions:
  disaster.trigger:
    description: Toestemming om rampen te activeren
    default: op
  disaster.bypasscooldown:
    description: Omzeil de wachttijd tussen rampen
    default: op

